[phases.setup]
nixPkgs = ["nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install --ignore-scripts"]

[phases.build]
cmds = ["cd artifacts/api-server && node build.mjs"]

[start]
cmd = "node artifacts/api-server/dist/bot.mjs"
